### PR TITLE
Just nested container directives

### PR DESCRIPTION
**Pull request by instopunk**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

TODO

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Welcome @instopunk! 👋 
Could you add some context and description around what your are trying to solve here?
Is this PR related to https://github.com/micromark/micromark-extension-directive/issues/8? Or something else entirely?

**Comment by instopunk** [comment]
@ChristianMurphy Hello! I apologize for such a bad PR. I'm new to github and I'm just trying to figure out how everything is set up here =) Yes, these changes are related to the issue #8 you mentioned. I think I managed to solve it and it works for me. But I still don't know how to properly cover these changes with tests(

**Comment by ChristianMurphy** [comment]
> But I still don't know how to properly cover these changes with tests

To test it add examples in https://github.com/micromark/micromark-extension-directive/blob/main/test/index.js
which rely on the new behavior you added.

---

Also based off https://github.com/micromark/micromark-extension-directive/issues/8#issuecomment-789809866
It sounds like the intent of that discussion may have been do have this behavior behind a flag? @wooorm would be able to confirm.

**Comment by ChristianMurphy** [comment]
@instopunk is you're still interested this would be a good change to have.
If you have follow up questions on testing or how to put a feature behind an option/flag feel free to ask.

**Comment by instopunk** [comment]
@ChristianMurphy, oh thanks! I just need a little time to figure it out

**Pull request closed without merging**
